version: '2.3'
services:
  mysqldbserver:
    build:
      context: .
      dockerfile: mysqldb.dockerfile
    ports:
    - 3308:3306
    environment:
      MYSQL_DATABASE: ManagementProduct
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: myrootpassword
    container_name: mysqldbserver
  rabbit1:
    image: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: /
    ports:
    - 15673:15672
    - 5673:5672
    volumes:
    - ./enabled_plugins:/etc/rabbitmq/enabled_plugins

