server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/ManagementProduct
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        web: debug
configuration:
  rabbitmq:
    exchangesInsertion: x.management
    routing-key-insertion: management
    queue-insertion: q.management.insert
    exchanges-retrieve: x.management.get
    routing-key-retrieve: management.get
    queue-retrieve: q.management.get
    hostname: localhost
    port: 5672
    username: admin
    password: admin